name: Publish to Qiita

on:
  push:
    branches:
      - main
    paths:
      - 'docs/qiita/**.md'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: noraworld/github-to-qiita@v1.0.1
        with:
          dir: docs/qiita
          qiita_access_token: ${{ secrets.QIITA_TOKEN }}
